core/urls.py
from django.urls import path
from .views import (Settings, UserData, UserPassword, Address, Orders, OrderDetail, OrderCreate,
		Cart, CartPlus, CartMinus, CartRemove)

app_name = 'core'

urlpatterns = [
    path('cart', Cart.as_view(), name='cart'),
    path('cart-plus/<str:pk>', CartPlus.as_view(), name='cart_plus'),
    path('cart-minus/<str:pk>', CartMinus.as_view(), name='cart_minus'),
    path('cart-remove/<str:pk>', CartRemove.as_view(), name='cart_remove'),
    path('orders', Orders.as_view(), name='orders'),
    path('order-detail/<str:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order-create/<str:pk>', OrderCreate.as_view(), name='order_create'),
    path('address', Address.as_view(), name='address'),
    path('settings', Settings.as_view(), name='settings'),
    path('settings/data', UserData.as_view(), name='user_data'),
    path('settings/password', UserPassword.as_view(), name='user_password'),
]
 

login/urls.py
from django.urls import path
from .views import Signup, Signin, Signout, ForgotPassword, ResetPassword, ConfirmToken, ConfirmEmail, Suspended

app_name = 'login'

urlpatterns = [
    path('suspended/<str:email>', Suspended.as_view(), name='suspended'),
    path('login', Signin.as_view(), name='signin'),
    path('signout',  Signout.as_view(), name='signout'),
    path('signup',  Signup.as_view(), name='signup'),
    path('forgot-password',  ForgotPassword.as_view(), name='forgot-password'),
    path('reset-password/<str:token>',  ResetPassword.as_view(), name='reset-password'),
    path('confirm-token/<str:user_id>', ConfirmToken.as_view(), name='confirm-token'),
    path('confirm-email/<str:user_id>/<str:token>',  ConfirmEmail.as_view(), name='confirm-email'),
]
 

main/urls.py
from django.urls import path
from .views import Index, Products, ProductDetail, EmailSubscribe, ContactUs, BecomeSeller

app_name = 'main'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('become-seller', BecomeSeller.as_view(), name='become_seller'),
    path('email-subscribe', EmailSubscribe.as_view(), name='email_subscribe'),
    path('contact-us', ContactUs.as_view(), name='contact_us'),
    path('products', Products.as_view(), name='products'),
    path('products/<str:pk>', ProductDetail.as_view(), name='product_detail'),
]

mstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('core.urls')),
    path('', include('login.urls')),
    path('seller/', include('seller.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.error_404'
# handler500 = 'main.views.error_500'

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms


class EmailForm(forms.Form):
	email = forms.EmailField(required=False, label='', max_length=100,  widget=forms.EmailInput(attrs={
		'placeholder':'Email Address', 'class': 'form-control', 'id': 'emailAddress'
		}))



class ContactUsForm(forms.Form):
	email = forms.EmailField(required=False, label='', max_length=100,  widget=forms.EmailInput(attrs={
		'placeholder':'Email Address', 'class': 'form-control', 'id': 'emailAddress'
		}))

	message = forms.CharField(required=False, label='', max_length=1000,  widget=forms.Textarea(attrs={
		'rows': 5, 'cols': 40, 'placeholder':'Message', 'class': 'form-control'
		}))

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if not email or len(email) == 0:
			raise forms.ValidationError('Email is required')
		return email
		
	def clean_message(self):
		message = self.cleaned_data.get('message')
		if not message or len(message) == 0:
			raise forms.ValidationError('Message is required')
		return message

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.db.utils import IntegrityError
from django.contrib import messages
from django.http import Http404, HttpResponse, HttpResponseRedirect, QueryDict
from django.db.models import Q
from django.shortcuts import get_object_or_404
from core.models import Category, SubCategory, Product, User, Email, ContactUs as ContactUsModel, Cart
from utils import popular_categories, popular_categories_and_sub, paginate_page, is_mobile
from .forms import EmailForm, ContactUsForm

# Create your views here.


def error_404(request, exception):
    return render(request, 'main/404.html', status=404)

# def error_500(request):
    # return render(request, 'main/500.html', status=500)


class Base(View):
	base_context = {**popular_categories(), 'cart_items': [], 'product_in_cart': []}
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			items = Cart.objects.filter(buyer=request.user, checked_out=False, product__is_approved=True)
			self.base_context['cart_items'] = items
			product_in_cart = set()
			for item in items:
				if item.product.is_approved:
					product_in_cart.add(item.product.pk)
			self.base_context['product_in_cart'] = product_in_cart

		data = self.get_request(request, *args, **kwargs)
		if isinstance(data, (HttpResponseRedirect, HttpResponse)):
			return data

		request_obj, template, context = data
		context.update(self.base_context)
		return render(request_obj, template, context)

	def post(self, request, *args, **kwargs):
		data = self.post_request(request, *args, **kwargs)
		if isinstance(data, (HttpResponseRedirect, HttpResponse)):
			return data
		return render(*data)

	# base_context = {**popular_categories(), 'cart_items': [], 'product_in_cart': []}
	# def body(self, request, *args, **kwargs):
	# 	if request.user.is_authenticated:
	# 		items = Cart.objects.filter(buyer=request.user, checked_out=False, product__is_approved=True)
	# 		self.base_context['cart_items'] = items
	# 		product_in_cart = set()
	# 		for item in items:
	# 			if item.product.is_approved:
	# 				product_in_cart.add(item.product.pk)
	# 		self.base_context['product_in_cart'] = product_in_cart

	# 	data = self.get_request(request, *args, **kwargs)
	# 	if isinstance(data, (HttpResponseRedirect, HttpResponse)):
	# 		return data

	# 	request_obj, template, context = data
	# 	context.update(self.base_context)
	# 	return render(request_obj, template, context)

	# def get(self, request, *args, **kwargs):
	# 	return self.body(request, *args, **kwargs)

	# def post(self, request, *args, **kwargs):
	# 	return self.body(request, *args, **kwargs)


		


class Index(Base):
	def get_request(self, request):
		is_mobile_device = is_mobile(request)
		if is_mobile_device:
			no_products  = 8
		else:
			no_products = 12

		products = Product.objects.filter(is_approved=True).order_by('ordered')[:no_products]
		return (request, 'main/index.html', {'products': products, 'email_form': EmailForm(), 'nav_home': 'green'})


class BecomeSeller(Base):
	def get_request(self, request):
		return (request, 'main/become_seller.html', {'nav_become_seller': 'green'})



class ProductDetail(Base):
	def get_request(self, request, pk):
		product = get_object_or_404(Product, pk=pk)
		btn_disable = False
		if not product.is_approved:
			if not request.user.is_authenticated or product.seller != request.user:
				raise Http404("The resource you requested does not exist")

			if request.user.is_authenticated and product.seller == request.user:
				messages.warning(request, 'The product request is not approved')
				btn_disable = True


		is_mobile_device = is_mobile(request)
		if is_mobile_device:
			no_products  = 4
		else:
			no_products = 6

		related_products = Product.objects\
		.filter(Q(sub_category=product.sub_category) & Q(is_approved=True))\
		.exclude(pk=product.pk).order_by('ordered')[:no_products]

		return (request, 'main/product_detail.html', {
			'product': product, 
			'products': related_products,
			'nav_products': 'green',
			'btn_disable': btn_disable,
		})


class Products(Base):
	def get_request(self, request):
		category_name = request.GET.get('category')
		sub_name = request.GET.get('sub')
		seller_id = request.GET.get('seller')
		search = request.GET.get('search')

		category = None
		sub_category = None
		seller = None
		agrs = ''

		has_no_filter_search = False

		if not search:

			if seller_id:
				seller = User.objects.filter(pk=seller_id).first()

			if category_name:
				category = Category.objects.filter(name=category_name).first()

				if sub_name:
					sub_category = SubCategory.objects.filter(Q(name=sub_name) & Q(category=category)).first()

			if sub_category and seller:
				agrs += f'&category={category_name}&sub={sub_name}&seller={seller_id}'
				the_products = Product.objects.filter(Q(sub_category=sub_category) & Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
			elif category and seller:
				agrs += f'&category={category_name}&sub={sub_name}&seller={seller_id}'
				the_products = Product.objects.filter(Q(sub_category__category=category) & Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
			elif sub_category:
				agrs += f'&category={category_name}&sub={sub_name}'
				the_products = Product.objects.filter(Q(sub_category=sub_category) & Q(is_approved=True)).order_by('ordered')
			elif seller:
				agrs += f'&seller={seller_id}'
				the_products = Product.objects.filter(Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
			elif category:
				agrs += f'&category={category_name}'
				the_products = Product.objects.filter(Q(sub_category__category=category) & Q(is_approved=True)).order_by('ordered')
			else:
				has_no_filter_search = True
				the_products = Product.objects.filter(is_approved=True).order_by('ordered')
		else:
			the_products = Product.objects.filter(Q(is_approved=True) & Q(name__icontains=search)).order_by('ordered')[:12]

		context = {
			**paginate_page(the_products, request, Http404, obj='products'),
			**popular_categories_and_sub(),
			'number_of_products': len(the_products),
			'url_args': agrs,
			'nav_products': 'green',
			'search_term': search,
			'has_no_filter_search': has_no_filter_search,
			'seller': seller,
		}

		return (request, 'main/products.html', context)



# class Products(Base):
# 	def get_request(self, request):
# 		category_name = request.GET.get('category')
# 		sub_name = request.GET.get('sub')
# 		seller_id = request.GET.get('seller')
# 		search = request.GET.get('search')

# 		category = None
# 		sub_category = None
# 		seller = None
# 		agrs = ''

# 		has_no_filter_search = False

# 		if not search:

# 			if seller_id:
# 				seller = User.objects.filter(pk=seller_id).first()

# 			if category_name:
# 				category = Category.objects.filter(name=category_name).first()

# 				if sub_name:
# 					sub_category = SubCategory.objects.filter(Q(name=sub_name) & Q(category=category)).first()

# 			if sub_category and seller:
# 				agrs += f'&category={category_name}&sub={sub_name}&seller={seller_id}'
# 				the_products = Product.objects.filter(Q(sub_category=sub_category) & Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
# 			elif category and seller:
# 				agrs += f'&category={category_name}&sub={sub_name}&seller={seller_id}'
# 				the_products = Product.objects.filter(Q(sub_category__category=category) & Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
# 			elif sub_category:
# 				agrs += f'&category={category_name}&sub={sub_name}'
# 				the_products = Product.objects.filter(Q(sub_category=sub_category) & Q(is_approved=True)).order_by('ordered')
# 			elif seller:
# 				agrs += f'&seller={seller_id}'
# 				the_products = Product.objects.filter(Q(seller=seller) & Q(is_approved=True)).order_by('ordered')
# 			elif category:
# 				agrs += f'&category={category_name}'
# 				the_products = Product.objects.filter(Q(sub_category__category=category) & Q(is_approved=True)).order_by('ordered')
# 			else:
# 				has_no_filter_search = True
# 				the_products = Product.objects.filter(is_approved=True).order_by('ordered')
# 		else:
# 			the_products = Product.objects.filter(Q(is_approved=True) & Q(name__icontains=search)).order_by('ordered')[:12]

# 		context = {
# 			**paginate_page(the_products, request, Http404, obj='products'),
# 			**popular_categories_and_sub(),
# 			'number_of_products': len(the_products),
# 			'url_args': agrs,
# 			'nav_products': 'green',
# 			'search_term': search,
# 			'has_no_filter_search': has_no_filter_search,
# 		}

# 		if seller:
# 			context['seller'] = seller_id
# 			context['seller_name'] = seller.name or "N/A"

# 		return (request, 'main/products.html', context)


class ContactUs(Base):
	def get_request(self, request):
		form = ContactUsForm()
		return (request, 'main/contact_us.html', {'form': form, 'nav_contact_us': 'green'})

	def post_request(self, request):
		form = ContactUsForm(request.POST)
		if form.is_valid():
			try:
				ContactUsModel.objects.create(email=form.cleaned_data.get('email'), message=form.cleaned_data.get('message'))
				messages.success(request, 'Message has been received')
				form = ContactUsForm()
				return (request, 'main/contact_us.html', {'form': form})

			except IntegrityError:
				messages.warning(request, 'Fill email and message appropriately')
				return (request, 'main/contact_us.html', {'form': form})


		messages.warning(request, 'Fill email and message appropriately')
		return (request, 'main/contact_us.html', {'form': form})


class EmailSubscribe(View):
	def get(self, request):
		return redirect(reverse('main:index'))

	def post(self, request):
		email_form = EmailForm(request.POST)
		if email_form.is_valid():
			try:
				Email.objects.create(email=email_form.cleaned_data.get('email'))
				messages.success(request, 'Email address has been added')
				return redirect(reverse('main:index'))

			except IntegrityError:

templates/main/become_seller.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Become Seller{% endblock %}
{% block content %}
<main>
    <section class="py-lg-16 py-10"
            style="background: url({% static 'img/hero custom.png' %})no-repeat; background-position: center; background-size: cover;">
        <div class="container">

            <div class="ps-lg-12 py-lg-7 col-xxl-5 col-md-7 py-14 px-8 text-xs-center">
              <h2 class="text-dark display-5 fw-bold mt-4">Start selling fast</h2>
              <p class="lead">Sell your product with us and get paid fast.</p>
              <a href="#" class="btn btn-dark mt-3">Sell Now <i class="feather-icon icon-arrow-right ms-1"></i></a>
            </div>

          </div>
      </div>
    </section>

    <section>
      <div class="container mt-10">
        <div class="row">
          <div class="col-lg-4">
            <div class="mb-8 mb-xl-0">
              <h3 class="h5 mb-3">
                Sell your products with easy
              </h3>
              <p>Get your order delivered to your doorstep at the earliest from FreshCart pickup stores near you.</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="mb-8 mb-xl-0">
              <h3 class="h5 mb-3">Get paid fast</h3>
              <p>Cheaper prices than your local supermarket, great cashback offers to top it off. Get best pricess &
                offers.
              </p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="mb-8 mb-xl-0">
              <h3 class="h5 mb-3">It's free to sell</h3>
              <p>Choose from 5000+ products across food, personal care, household, bakery, veg and non-veg & other
                categories.</p>
            </div>
          </div>
        </div>
      </div>
    </section>


  <section>
    <div class="container mt-10">
      <div class="row">
        <div class="col-12">

          <div class="mb-4 bg-light d-lg-flex justify-content-between align-items-center rounded">
            <div class="  p-10">

              <h2 class="mb-1 fw-bold">Have products</h2>
              <p class="mb-0 lead">Start salling with us and sell your products faster and easier.
              </p>
              <a href="#" class="btn btn-dark mt-5">Start Selling</a>

            </div>
            <div class="p-6 d-lg-block d-none"><img src="{% static 'assets/images/svg-graphics/store-graphics.svg' %}" alt=""
                class="img-fluid">
            </div>
          </div>


        </div>
      </div>
    </div>
  </section>

  <section class="bg-dark mt-10"
    style="background:url({% static 'assets/images/svg-graphics/pattern.svg' %})no-repeat; background-size: cover; background-position: center;">
    <div class="container">
       <!-- row -->
      <div class="row">
        <div class="offset-lg-1 col-lg-10">

          <div class="row align-items-center">
             <!-- col -->
            <div class="col-md-6">
              <div class="text-white mt-8 mt-lg-0">
                <h2 class="h2 text-white  my-4">Get top deals, latest trends,
                  and more.</h2>
                <p class="text-white-50">Join our email subscription now to get updates on promotions
                  and coupons.</p>
                   <!-- form -->
                <form action="{% url 'main:email_subscribe' %}" method="post" class="row g-3">
                  {% csrf_token %}

                  <div class="col-6">
                     <!-- input -->
                    <label for="emailAddress" class="visually-hidden">Email Address</label>
                    {{ email_form.email }}
                  </div>
                   <!-- btn -->
                  <div class="col-auto">
                    <button type="submit" class="btn btn-primary mb-3">Sign Up</button>
                  </div>
                </form>
              </div>
            </div>
             <!-- col -->
            <div class="col-md-6">
              <div class="text-center">
                 <!-- img -->
                <img src="{% static 'img/email-removebg.png' %}" alt="" style="filter: brightness(85%);" class="img-fluid d-md-block d-none">
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

templates/main/contact_us.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Contact us{% endblock %}

{% block content %}
  <main>
  <!-- section -->
  <section>
    <!-- container -->
    <div class="container">
     <div class="row">

        <div class="col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <div class="mb-6">
              <!-- heading -->
              <h2 class="mb-0">Contact Us</h2>
            </div>
            <div>
            <div class="pe-lg-14">
              <!-- heading -->
              <form action="{% url 'main:contact_us' %}" method="post" class="">
                {% csrf_token %}
                <!-- input -->
                <div class="mb-3">
                  <label class="form-label">Email</label>
                  {{ form.email }}
                  {% if form.email.errors %}
                  {% for error in form.email.errors %}
                    <span class="text-danger small">{{ error }}</span>
                  {% endfor %}
                  {% endif %}
                </div>
                <!-- input -->
                <div class="mb-3 col">
                  <label class="form-label">Message</label>
                  {{ form.message }}
                  {% if form.message.errors %}
                  {% for error in form.message.errors %}
                    <span class="text-danger small">{{ error }}</span>
                  {% endfor %}
                  {% endif %}
                </div>
                <!-- input -->
                <div class="col-12">
                  <button class="btn btn-primary">Send</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

    </div>
</div>



  </section>
</main>
{% endblock %}

templates/main/product_detail.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Product Detail{% endblock %}

{% block content %}

<main>
  <section class="mt-8">
    <div class="container">
      <div class="row">

        <div class="col-md-6">
          <!-- img slide -->
          <div class="product" id="product">
            <div class="d-flex align-items-center justify-content-center">
              <img src="{{ product.image|image_url }}" class="img-fluid" style="max-height: 500px" alt="{{ product.name }}">
            </div>
            <!-- <div>
              <div class="zoom" onmousemove="zoom(event)"
                style="background-image: url({% static 'assets/images/products/product-single-img-2.jpg' %})">
                <img src="{% static 'assets/images/products/product-single-img-2.jpg' %}" alt="">
              </div>
            </div>
            <div>
              <div class="zoom" onmousemove="zoom(event)"
                style="background-image: url({% static 'assets/images/products/product-single-img-3.jpg' %})">
                <img src="{% static 'assets/images/products/product-single-img-3.jpg' %}" alt="">
              </div>
            </div>
            <div>
              <div class="zoom" onmousemove="zoom(event)"
                style="background-image: url({% static 'assets/images/products/product-single-img-4.jpg' %})">
                <img src="{% static 'assets/images/products/product-single-img-4.jpg' %}" alt="">
              </div> -->
            </div>
          </div>
          <!-- product tools -->
          <!-- <div class="product-tools">
            <div class="thumbnails row g-3" id="productThumbnails">
              <div class="col-3">
                <div class="thumbnails-img">
                  <img src="{% static 'assets/images/products/product-single-img-1.jpg' %}" alt="">
                </div>
              </div>
              <div class="col-3">
                <div class="thumbnails-img">
                  <img src="{% static 'assets/images/products/product-single-img-2.jpg' %}" alt="">
                </div>
              </div>
              <div class="col-3">
                <div class="thumbnails-img">
                  <img src="{% static 'assets/images/products/product-single-img-3.jpg' %}" alt="">
                </div>
              </div>
              <div class="col-3">
                <div class="thumbnails-img">
                  <img src="{% static 'assets/images/products/product-single-img-4.jpg' %}" alt="">
                </div>
              </div>
            </div>
          </div> -->
        <!-- </div> -->
        <div class="col-md-6">
          <div class="ps-lg-10 mt-6 mt-md-0">
            <!-- seller name -->
            <div class="mt-3 mb-5">
                <div class="ellipsis-oneline">
                  <a href="/products?seller={{ product.seller.id }}" class="text-nature">
                    <img src="{{ product.seller.image|image_user_url }}" alt="" class="avatar avatar-md rounded-circle">
                  {{ product.seller.name }}</a>
                </div>
              </div>
            <!-- heading -->
            <h1 class="mb-1">{{ product.name }} </h1>
            <!-- <div class="mb-4">
               <small class="text-warning"> <i class="bi bi-star-fill"></i>
                <i class="bi bi-star-fill"></i>
                <i class="bi bi-star-fill"></i>
                <i class="bi bi-star-fill"></i>
                <i class="bi bi-star-half"></i></small><a href="#" class="ms-2">(30 reviews)</a></div> -->
            <div class="fs-4">
              <!-- price --><span class="fw-bold text-dark">₦{{ product.price|format_price }}</span> 
              <div class="col-xxl-4 col-lg-4 col-md-5 col-5 d-grid my-6">
                    {% if request.user.is_authenticated %}

                <button onclick="add_product_cart(this, '{{ product.pk }}')" class="btn btn-primary rounded-pill {% if product.pk in product_in_cart %}d-none{% endif %} {% if btn_disable %}disabled{% endif %}">
                      <i class="bi bi-plus-lg me-1"></i>Add
                    </button>

                    <button onclick="remove_product_cart(this, '{{ product.pk }}')" class="btn btn-primary rounded-pill {% if product.pk not in product_in_cart %}d-none{% endif %} {% if btn_disable %}disabled{% endif %}">
                      <i class="bi bi-dash-lg me-1"></i>Remove
                    </button>

                    <button class="btn btn-primary rounded-pill d-none">
                      <div class="spinner-border" style="width: 22.5px; height: 22.5px;" role="status">
                          <span class="sr-only"></span>
                        </div>
                    </button>
                    {% else %}

                    <a  href="{% url 'login:signin' %}?next={% url 'main:product_detail' pk=product.pk %}&login_cart=true" class="btn btn-primary rounded-pill {% if product.pk in product_in_cart %}d-none{% endif %} {% if btn_disable %}disabled{% endif %}">
                      <i class="bi bi-plus-lg me-1"></i>Add
                    </a>

                    <a href="{% url 'login:signin' %}?next={% url 'main:product_detail' pk=product.pk %}&login_cart=true" class="btn btn-primary rounded-pill {% if product.pk not in product_in_cart %}d-none{% endif %} {% if btn_disable %}disabled{% endif %}">
                      <i class="bi bi-dash-lg me-1"></i>Remove
                    </a>

                    {% endif %}

              </div>
              <!-- <span
                class="text-decoration-line-through text-muted">$35</span><span><small class="fs-6 ms-2 text-danger">26%
                  Off</small></span> -->
            </div>
            <!-- hr -->
            <!-- <hr class="my-6"> -->
           <!--  <div class="mb-5"><button type="button" class="btn btn-outline-secondary">250g</button>
             <button type="button" class="btn btn-outline-secondary">500g</button>
             <button type="button" class="btn btn-outline-secondary">1kg</button></div>
              <div> -->


                <!-- input -->
                <!-- <div class="input-group input-spinner  ">
                  <input type="button" value="-" class="button-minus  btn  btn-sm " data-field="quantity">
                  <input type="number" step="1" max="10" value="1" name="quantity" class="quantity-field form-control-sm form-input   ">
                  <input type="button" value="+" class="button-plus btn btn-sm " data-field="quantity">
                </div> -->

            <!-- </div> -->
            <!-- <div class="mt-3 row justify-content-start g-2 align-items-center"> -->

              <!-- <div class="col-xxl-4 col-lg-4 col-md-5 col-5 d-grid">
                <button type="button" class="btn btn-primary"><i class="feather-icon icon-shopping-bag me-2"></i>Order</button>
              </div> -->
              <!-- <div class="col-md-4 col-4">
                <a class="btn btn-light " href="#" data-bs-toggle="tooltip" data-bs-html="true" aria-label="Compare"><i class="bi bi-arrow-left-right"></i></a>
                <a class="btn btn-light " href="shop-wishlist.html" data-bs-toggle="tooltip" data-bs-html="true" aria-label="Wishlist"><i class="feather-icon icon-heart"></i></a>
              </div> -->
            <!-- </div> -->
            <!-- hr -->
            <hr class="my-6">
            <div>
              <!-- table -->
              <table class="table table-borderless mb-0">

                <tbody>
                  <tr>
                    <td>Product Code:</td>
                    <td>{{ product.id }}</td>
                  </tr>
                  <tr>
                    <td>Location:</td>
                    <td>{{ product.state }}</td>
                  </tr>
                  <tr>
                    <td>Category:</td>
                    <td>{{ product.sub_category.category.name }}</td>
                  </tr>
                  <tr>
                    <td>Sub Category:</td>
                    <td>{{ product.sub_category.name }}</td>
                  </tr>
                </tbody>
              </table>

            </div>
            <!-- <div class="mt-8">
              <div class="dropdown">
                <a class="btn btn-outline-secondary dropdown-toggle" href="#" role="button"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  Share
                </a>

                <ul class="dropdown-menu" >
                  <li><a class="dropdown-item" href="#"><i class="bi bi-facebook me-2"></i>Facebook</a></li>
                  <li><a class="dropdown-item" href="#"><i class="bi bi-twitter me-2"></i>Twitter</a></li>
                  <li><a class="dropdown-item" href="#"><i class="bi bi-instagram me-2"></i>Instagram</a></li>
                </ul>
              </div>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </section>
<section>
   <div class="container">
              <div class="my-8">
                <div class="mb-5">
                  <!-- text -->
                  <h4 class="mb-1">Description</h4>
                  <p class="mb-0">{{ product.description|safe }}</p>
                </div>
                <div class="mb-5">
                  <h5 class="mb-1">Seller</h5>
                  <p class="mb-0">{{ product.seller.description }}</p>
                </div>
                <div>
                  <h5 class="mb-1">Disclaimer</h5>
                  <p class="mb-0">Image shown is a representation and may slightly vary from the actual product. Every
                    effort
                    is made to maintain accuracy of all information displayed.</p>
                </div>
              </div>
            </div>
</section>
  <!-- section -->
  <section class="my-lg-14 my-14">
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-12">
          <!-- heading -->
          <h3>Related Items</h3>
        </div>
      </div>
      <!-- row -->
      {% with col=3 %}
            {% include '../include/product_card.html' with col=col %}
          {% endwith%}
    </div>
  </section>

</main>

{% endblock %}