core/urls.py
from django.urls import path
from .views import (Settings, UserData, UserPassword, Address, Orders, OrderDetail, OrderCreate,
		Cart, CartPlus, CartMinus, CartRemove)

app_name = 'core'

urlpatterns = [
    path('cart', Cart.as_view(), name='cart'),
    path('cart-plus/<str:pk>', CartPlus.as_view(), name='cart_plus'),
    path('cart-minus/<str:pk>', CartMinus.as_view(), name='cart_minus'),
    path('cart-remove/<str:pk>', CartRemove.as_view(), name='cart_remove'),
    path('orders', Orders.as_view(), name='orders'),
    path('order-detail/<str:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order-create/<str:pk>', OrderCreate.as_view(), name='order_create'),
    path('address', Address.as_view(), name='address'),
    path('settings', Settings.as_view(), name='settings'),
    path('settings/data', UserData.as_view(), name='user_data'),
    path('settings/password', UserPassword.as_view(), name='user_password'),
]
 

login/urls.py
from django.urls import path
from .views import Signup, Signin, Signout, ForgotPassword, ResetPassword, ConfirmToken, ConfirmEmail, Suspended

app_name = 'login'

urlpatterns = [
    path('suspended/<str:email>', Suspended.as_view(), name='suspended'),
    path('login', Signin.as_view(), name='signin'),
    path('signout',  Signout.as_view(), name='signout'),
    path('signup',  Signup.as_view(), name='signup'),
    path('forgot-password',  ForgotPassword.as_view(), name='forgot-password'),
    path('reset-password/<str:token>',  ResetPassword.as_view(), name='reset-password'),
    path('confirm-token/<str:user_id>', ConfirmToken.as_view(), name='confirm-token'),
    path('confirm-email/<str:user_id>/<str:token>',  ConfirmEmail.as_view(), name='confirm-email'),
]
 

main/urls.py
from django.urls import path
from .views import Index, Products, ProductDetail, EmailSubscribe, ContactUs, BecomeSeller

app_name = 'main'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('become-seller', BecomeSeller.as_view(), name='become_seller'),
    path('email-subscribe', EmailSubscribe.as_view(), name='email_subscribe'),
    path('contact-us', ContactUs.as_view(), name='contact_us'),
    path('products', Products.as_view(), name='products'),
    path('products/<str:pk>', ProductDetail.as_view(), name='product_detail'),
]

mstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('core.urls')),
    path('', include('login.urls')),
    path('seller/', include('seller.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.error_404'
# handler500 = 'main.views.error_500'

templates/include/categories.html
{% load static %}

<div class="offcanvas-body ps-lg-2 pt-lg-0">
  <div class="mb-8">
    <!-- title -->
    <h5 class="mb-3">Categories</h5>
    <!-- nav -->
    <ul class="nav nav-category" id="categoryCollapseMenu">
      {% for category_and_sub in categories_and_sub %}
        {% if category_and_sub.1 %}
          <li class="nav-item border-bottom w-100 {% if category_and_sub.0 != request.GET.category %}collapsed{% endif %}" data-bs-toggle="collapse"
            data-bs-target="#{{ category_and_sub.0 }}" aria-expanded="{% if category_and_sub.0 == request.GET.category %}true{% else %}false{% endif %}" aria-controls="{{ category_and_sub.0 }}">
            <a href="#" class="nav-link {% if category_and_sub.0 == request.GET.category %}green{% endif %}">{{ category_and_sub.0 }}<i class="feather-icon icon-chevron-right"></i></a>
            <!-- accordion collapse -->
            <div id="{{ category_and_sub.0 }}" class="accordion-collapse collapse {% if category_and_sub.0 == request.GET.category %}show{% endif %}"
              data-bs-parent="#categoryCollapseMenu">
              <div>
                <!-- nav -->
                <ul class="nav flex-column ms-3">
                  {% for sub in category_and_sub.1 %}
                    <!-- nav item -->
                    <li class="nav-item"><a href="?category={{ category_and_sub.0 }}&sub={{ sub }}&seller={{ seller.pk }}" class="nav-link {% if sub == request.GET.sub %}green{% endif %}" onclick="refreshPage('{{ category_and_sub.0 }}', '{{ sub }}', '{{ seller.pk }}')">{{ sub }}</a></li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

<script>
  function refreshPage(category, sub, seller) {
    var url = window.location.href.split('?')[0] + '?category=' + category;
    if (sub) {
      url += '&sub=' + sub;
    }
    if (seller) {
      url += '&seller=' + seller;
    }
    window.location.href = url;
  }
</script>

templates/include/footer.html
{% load static %}

<footer class="footer">
  <div class="container">
    <div class="g-4 py-4 text-center">
        <h6 class="mb-4">Categories</h6>
        <div class="text-center">
              {% for category in categories %}
              <a href="/products?category={{ category }}" class="me-4 text-nature">{{ category.name }}</a>
              {% endfor %}
          </div>
      </div>
    <div class="border-top py-4">
      <div class="row align-items-center">
        <div class="col-md-6"><span class="small text-muted">Copyright <span id="copyright-year"></span> © Nime enterprise.  All rights reserved.</span></div>
        <div class="col-md-6">
          <ul class="list-inline text-md-end mb-0 small mt-3 mt-md-0">
            <li class="list-inline-item text-muted">Follow us on</li>
            <li class="list-inline-item me-1">
              <a href="#!" class="btn btn-xs btn-social btn-icon"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-facebook" viewBox="0 0 16 16">
                  <path
                    d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                </svg></a></li>
            <li class="list-inline-item me-1">
              <a href="#!" class="btn btn-xs btn-social btn-icon"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-twitter" viewBox="0 0 16 16">
                  <path
                    d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                </svg></a></li>
            <li class="list-inline-item">
              <a href="#!" class="btn btn-xs btn-social btn-icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-instagram" viewBox="0 0 16 16">
                  <path
                    d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                </svg></a></li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</footer>

<script>
let currentYear = new Date().getFullYear();

let year = document.getElementById("copyright-year");
year.innerText = `${currentYear}`;

</script>

templates/include/little_modelbar.html
{% load static %}
  
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasAccount" aria-labelledby="offcanvasAccountLabel">
    <!-- offcanvas header -->
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasAccountLabel">Menu</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
      <!-- offcanvas body -->
    <div class="offcanvas-body">
      <ul class="nav flex-column nav-pills nav-pills-dark">
         <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ cart }}" aria-current="page" href="/cart"><i
              class="feather-icon icon-shopping-cart me-2"></i>Your Cart</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ orders }}" aria-current="page" href="/orders"><i
              class="feather-icon icon-shopping-bag me-2"></i>Your Orders</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ settings }}" href="/settings"><i class="feather-icon icon-settings me-2"></i>Settings</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ address }}" href="/address"><i class="feather-icon icon-map-pin me-2"></i>Address</a>
        </li>
      </ul>
      <hr class="my-6">
      <div>
          <!-- nav  -->
        <ul class="nav flex-column nav-pills nav-pills-dark">
            <!-- nav item -->
          <li class="nav-item">
            <a class="nav-link " href="/signout"><i class="feather-icon icon-log-out me-2"></i>Log out</a>
          </li>

        </ul>
      </div>
    </div>
  </div>

templates/include/little_seller_modelbar.html
{% load static %}
  
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasAccount" aria-labelledby="offcanvasAccountLabel">
    <!-- offcanvas header -->
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasAccountLabel">Menu</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
      <!-- offcanvas body -->
    <div class="offcanvas-body">
      <ul class="nav flex-column nav-pills nav-pills-dark">
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link  {{ dashboard }}" aria-current="page" href="/seller/dashboard"><i
            class="feather-icon icon-home me-2"></i>Dashboard</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ products }}" href="/seller/products"><i
            class="feather-icon icon-shopping-bag me-2"></i>Products</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ orders }}" href="/seller/orders"><i
            class="feather-icon icon-shopping-cart me-2"></i>Orders</a>
        </li>
          <!-- nav item -->
        <li class="nav-item">
          <a class="nav-link {{ description }}" href="/seller/description"><i
            class="feather-icon icon-align-left me-2"></i>Description</a>
        </li>
      </ul>
      <hr class="my-6">
      <div>
          <!-- nav  -->
        <ul class="nav flex-column nav-pills nav-pills-dark">
            <!-- nav item -->
          <li class="nav-item">
            <a class="nav-link " href="/signout"><i class="feather-icon icon-log-out me-2"></i>Log out</a>
          </li>

        </ul>
      </div>
    </div>
  </div>

templates/include/little_seller_sidebar.html
{% load static %}

<div class="col-lg-3 col-md-4 col-12 border-end  d-none d-md-block">
  <div class="pt-10 pe-lg-10">
    <!-- nav item -->
    <ul class="nav flex-column nav-pills nav-pills-dark">
      <li class="nav-item">
        <a class="nav-link  {{ dashboard }}" aria-current="page" href="/seller/dashboard"><i
            class="feather-icon icon-home me-2"></i>Dashboard</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link {{ products }}" href="/seller/products"><i
            class="feather-icon icon-shopping-bag me-2"></i>Products</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link {{ orders }}" href="/seller/orders"><i
            class="feather-icon icon-shopping-cart me-2"></i>Orders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{ description }}" href="/seller/description"><i
            class="feather-icon icon-align-left me-2"></i>Description</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <hr>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link " href="{% url 'login:signout' %}"><i class="feather-icon icon-log-out me-2"></i>Log out</a>
      </li>
    </ul>
  </div>
</div>

templates/include/little_sidebar.html
{% load static %}

<div class="col-lg-3 col-md-4 col-12 border-end  d-none d-md-block">
  <div class="pt-10 pe-lg-10">
    <!-- nav item -->
    <ul class="nav flex-column nav-pills nav-pills-dark">
      <li class="nav-item">
        <a class="nav-link {{ cart }}" href="/cart"><i
            class="feather-icon icon-shopping-cart me-2"></i>Cart</a>
      </li>
      <li class="nav-item">
        <a class="nav-link  {{ orders }}" aria-current="page" href="/orders"><i
            class="feather-icon icon-shopping-bag me-2"></i>Your Orders</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link {{ settings }}" href="/settings"><i
            class="feather-icon icon-settings me-2"></i>Settings</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link {{ address }}" href="/address"><i
            class="feather-icon icon-map-pin me-2"></i>Address</a>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <hr>
      </li>
      <!-- nav item -->
      <li class="nav-item">
        <a class="nav-link " href="{% url 'login:signout' %}"><i class="feather-icon icon-log-out me-2"></i>Log out</a>
      </li>
    </ul>
  </div>
</div>

templates/include/navbar_auth.html
{% load static %}
  {% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %} my-0 rounded-0 text-center" role="alert">
    {{ message }}
    </div>
  {% endfor %}
  {% endif %}
<div class="border-bottom shadow-sm">
  <nav class="navbar navbar-light py-2">
    <div class="container justify-content-center justify-content-lg-between">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo-removebg-crop.png' %}" style="height: 45px" alt="Nime Enterprise">
      </a>
      <span class="navbar-text d-sm-inline d-none">
        {{ nav_text }} <a href="{{ nav_link }}">{{ nav_value }}</a>
      </span>
    </div>
  </nav>
</div>

templates/include/orders_list.html
{% load static %}
{% load custom_filters %}

 <div class="table-responsive">
  <table class="table table-centered table-hover text-nowrap table-borderless mb-0 table-with-checkbox">
    <thead class="bg-light">
      <tr>
        <th>Product</th>
        <th>Customer</th>
        <th>Items</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% for ordered_product in order_product %}
        <td><a href="{% url 'main:product_detail' pk=ordered_product.product.id %}" class="text-inherit text-decoration-none">{{ ordered_product.product.name }}</a></td>
        <td>{{ ordered_product.buyer.name|default:'-' }}</td>
        <td>{{ ordered_product.quantity }}</td>
        <td>{{ ordered_product.date|date:"F j, Y" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

templates/include/product_card.html
{% load static %}
{% load custom_filters %}


<div class="row g-4 row-cols-lg-{{ col }} row-cols-{{ col|subtract:2 }} row-cols-md-{{ col|subtract:1}}">
    {% for product in products %}
    <div class="col">
        <div class="card card-product">
            <div class="card-body">
              {% if not request.GET.seller %}
              <div class="ellipsis-oneline mb-3">
                <a href="products?seller={{ product.seller.id }}" class="text-nature">
                  <img src="{{ product.seller.image|image_user_url }}" alt="" class="avatar avatar-sm rounded-circle">
                {{ product.seller.name }}</a>
              </div>
              {% endif %}

              <a href="{% url 'main:product_detail' pk=product.id %}" class="text-inherit text-decoration-none">
                <div class="text-center position-relative">
                    <img src="{{ product.image|image_url }}" alt="{{ product.name }}" class="mb-3 img-fluid"
                            style="height: 200px">
                </div>

                <!-- <div class="text-small mb-1">
                    <a href="{% url 'main:product_detail' product.id %}"
                        class="text-decoration-none text-muted">
                        <small class="ellipsis-oneline">{{ product.sub_category.category.name }}</small>
                    </a>
                </div> -->

                <div class="d-flex align-items-center mt-3 text-muted">
                      <i class="bi bi-geo-alt-fill me-1"></i>
                      <span class="text-dark ellipsis-oneline">{{ product.state|default:"N/A" }}</span>
                </div>
                <h2 class="fs-6 mt-2">
                    <div class="ellipsis-oneline">{{ product.name }}</div>
                </h2>
              </a>
                
                
                <div class="d-flex justify-content-between align-items-center mt-4">
                    <span class="text-dark ellipsis-oneline">₦{{ product.price|format_price }}</span>
                    {% if request.user.is_authenticated %}
                    <button onclick="add_product_cart(this, '{{ product.pk }}')" class="btn btn-primary btn-sm {% if product.pk in product_in_cart %}d-none{% endif %}">
                      <i class="bi bi-plus-lg me-1"></i>Add
                    </button>

                    <button onclick="remove_product_cart(this, '{{ product.pk }}')" class="btn btn-primary btn-sm {% if product.pk not in product_in_cart %}d-none{% endif %}">
                      <i class="bi bi-dash-lg me-1"></i>Remove
                    </button>
                    <button class="btn btn-primary btn-sm d-none">
                      <div class="spinner-border" style="width: 19.5px; height: 19.5px;" role="status">
                          <span class="sr-only"></span>
                        </div>
                    </button>
                    {% else %}
                    <a href="{% url 'login:signin' %}?next={% url 'main:product_detail' pk=product.pk %}&login_cart=true" class="btn btn-primary btn-sm {% if product.pk in product_in_cart %}d-none{% endif %}">
                      <i class="bi bi-plus-lg me-1"></i>Add
                    </a>

                    <a  href="{% url 'login:signin' %}?next={% url 'main:product_detail' pk=product.pk %}&login_cart=true"  class="btn btn-primary btn-sm {% if product.pk not in product_in_cart %}d-none{% endif %}">
                      <i class="bi bi-dash-lg me-1"></i>Remove
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>