core/urls.py
from django.urls import path
from .views import (Settings, UserData, UserPassword, Address, Orders, OrderDetail, OrderCreate,
		Cart, CartPlus, CartMinus, CartRemove)

app_name = 'core'

urlpatterns = [
    path('cart', Cart.as_view(), name='cart'),
    path('cart-plus/<str:pk>', CartPlus.as_view(), name='cart_plus'),
    path('cart-minus/<str:pk>', CartMinus.as_view(), name='cart_minus'),
    path('cart-remove/<str:pk>', CartRemove.as_view(), name='cart_remove'),
    path('orders', Orders.as_view(), name='orders'),
    path('order-detail/<str:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order-create/<str:pk>', OrderCreate.as_view(), name='order_create'),
    path('address', Address.as_view(), name='address'),
    path('settings', Settings.as_view(), name='settings'),
    path('settings/data', UserData.as_view(), name='user_data'),
    path('settings/password', UserPassword.as_view(), name='user_password'),
]
 

login/urls.py
from django.urls import path
from .views import Signup, Signin, Signout, ForgotPassword, ResetPassword, ConfirmToken, ConfirmEmail, Suspended

app_name = 'login'

urlpatterns = [
    path('suspended/<str:email>', Suspended.as_view(), name='suspended'),
    path('login', Signin.as_view(), name='signin'),
    path('signout',  Signout.as_view(), name='signout'),
    path('signup',  Signup.as_view(), name='signup'),
    path('forgot-password',  ForgotPassword.as_view(), name='forgot-password'),
    path('reset-password/<str:token>',  ResetPassword.as_view(), name='reset-password'),
    path('confirm-token/<str:user_id>', ConfirmToken.as_view(), name='confirm-token'),
    path('confirm-email/<str:user_id>/<str:token>',  ConfirmEmail.as_view(), name='confirm-email'),
]
 

main/urls.py
from django.urls import path
from .views import Index, Products, ProductDetail, EmailSubscribe, ContactUs, BecomeSeller

app_name = 'main'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('become-seller', BecomeSeller.as_view(), name='become_seller'),
    path('email-subscribe', EmailSubscribe.as_view(), name='email_subscribe'),
    path('contact-us', ContactUs.as_view(), name='contact_us'),
    path('products', Products.as_view(), name='products'),
    path('products/<str:pk>', ProductDetail.as_view(), name='product_detail'),
]

mstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('core.urls')),
    path('', include('login.urls')),
    path('seller/', include('seller.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.error_404'
# handler500 = 'main.views.error_500'

core/forms.py
from django import forms
from django.contrib import messages
from .models import User


class ProductDeleteForm(forms.Form):
	pk = forms.CharField(required=True, label='', max_length=100,  widget=forms.TextInput(attrs={
		'type': 'hidden'
		}))

class AddressForm(forms.Form):
	state = forms.CharField(required=True, label='', max_length=100,  widget=forms.TextInput(attrs={
		'placeholder':'State', 'class': 'form-control'
		}))

	address = forms.CharField(required=True, label='', max_length=1000,  widget=forms.TextInput(attrs={
		'placeholder':'Address', 'class': 'form-control'
		}))

	def clean_state(self):
		state = self.cleaned_data.get('state')
		if not state or len(state) == 0:
			raise forms.ValidationError('State is required')
		return state
		
	def clean_address(self):
		address = self.cleaned_data.get('address')
		if not address or len(address) == 0:
			raise forms.ValidationError('Address is required')
		return address


class UserDataForm(forms.Form):
	name = forms.CharField(required=True, label='', max_length=100,  widget=forms.TextInput(attrs={
		'placeholder':'Name', 'class': 'form-control'
		}))

	whatsapp_number = forms.CharField(required=True, label='', max_length=30,  widget=forms.TextInput(attrs={
		'placeholder':'Whatsapp', 'class': 'form-control'
		}))
	
	image = forms.ImageField(required=False, label='', widget=forms.FileInput(attrs={
		'class': 'form-control'
	}))

	def clean_name(self):
		name = self.cleaned_data.get('name')
		if not name or len(name) == 0:
			raise forms.ValidationError('Name is required')
		return name
		
	def clean_whatsapp_number(self):
		whatsapp_number = self.cleaned_data.get('whatsapp_number')
		if not whatsapp_number or len(whatsapp_number) == 0:
			raise forms.ValidationError('Whatsapp number is required')
		return whatsapp_number


class UserPasswordForm(forms.Form):
	password = forms.CharField(required=True, label='', max_length=128, widget=forms.PasswordInput(attrs={
		'placeholder':'**********', 'class': 'form-control',
		}))

	current_password = forms.CharField(required=True, label='', max_length=128, widget=forms.PasswordInput(attrs={
		'placeholder':'**********', 'class': 'form-control',
		}))

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user', '')
		super(UserPasswordForm, self).__init__(*args, **kwargs)

	def clean_password(self):
		password = self.cleaned_data.get('password')

		if not password or len(password) < 8:
			raise forms.ValidationError('Password should be greater than 7 characters')

		return password

	def clean_current_password(self):
		current_password = self.cleaned_data.get('current_password')

		if not self.user.check_password(current_password):
			print('invalid')
			raise forms.ValidationError('Invalid password')
		print('valid')
		return current_password
            

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User, Order, Product, Cart as CartModel
from .forms import UserDataForm, UserPasswordForm, AddressForm
from main.views import Base
# Create your views here.


class Cart(LoginRequiredMixin, Base):
	def get_request(self, request):
		items = CartModel.objects.filter(buyer=request.user, checked_out=False)
		total = 0
		for item in items:
			total += item.total_price()
		return (request, 'core/cart.html', {'cart_items': items, 'total': total, 'nav_account': 'green'})


class CartPlus(LoginRequiredMixin, Base):
	def get_request(self, request, pk):
		product = Product.objects.filter(pk=pk).first()
		if not product or not product.is_approved:
			return JsonResponse({'ok': False})

		total = 0
		cart_item, created = CartModel.objects.get_or_create(buyer=request.user, product=product, checked_out=False)
		if not created:
			cart_item.quantity += 1
			cart_item.save()

			items = CartModel.objects.filter(buyer=request.user, checked_out=False)
			
			for item in items:
				total += item.total_price()
		return JsonResponse({'ok': True, 'price': cart_item.product.price, 'total': total, 'quantity': cart_item.quantity})


class CartMinus(LoginRequiredMixin, Base):
	def get_request(self, request, pk):
		product = Product.objects.filter(pk=pk).first()
		if not product:
			return JsonResponse({'ok': False})

		cart_item = CartModel.objects.filter(buyer=request.user, product=product, checked_out=False).first()
		if not cart_item:
			return JsonResponse({'ok': False}) 
		cart_item.quantity = cart_item.quantity -1 if cart_item.quantity > 0 else 0
		cart_item.save()

		items = CartModel.objects.filter(buyer=request.user, checked_out=False)
		total = 0
		for item in items:
			total += item.total_price()
		return JsonResponse({'ok': True, 'price': cart_item.product.price, 'total': total, 'quantity': cart_item.quantity})


class CartRemove(LoginRequiredMixin, Base):
	def get_request(self, request, pk):
		product = Product.objects.filter(pk=pk).first()
		if not product:
			return JsonResponse({'ok': False})

		cart_item = CartModel.objects.filter(buyer=request.user, product=product, checked_out=False).first()
		if not cart_item:
			return JsonResponse({'ok': False}) 
		cart_item.delete()
		return JsonResponse({'ok': True})


# lots of bugs
class OrderCreate(LoginRequiredMixin, Base):
	def get_request(self, request, pk):
		return redirect(reverse('core:order_detail', kwargs={'pk': pk}))

	def post_request(self, request, pk):
		# body
		# return redirect(reverse('core:order_detail', kwargs={'pk':order.pk}))
		pass


class OrderDetail(LoginRequiredMixin, Base):
	def get_request(self, request, pk):
		""" This order details creates an order if given product id"""
		order = Order.objects.filter(pk=pk).first()
		if order:
			return (request, 'core/order_detail.html', {'order': order, 'nav_account': 'green'})
		messages.warning(request, 'Click order if you want to continue your request')
		return redirect(reverse('main:product_detail', kwargs={'pk': pk}))


class Orders(LoginRequiredMixin, Base):
	def get_request(self, request):
		orders = Order.objects.filter(buyer=request.user.id)
		for order in orders:
			print(order.get_total_price_now())
		return (request, 'core/orders.html', {'orders': orders, 'nav_account': 'green'})


class Address(LoginRequiredMixin, Base):
	def get_request(self, request):
		user = request.user
		address_form = AddressForm({'state': user.state, 'address': user.address})
		return (request, 'core/address.html', {'address_form': address_form, 'nav_account': 'green'})

	def post_request(self, request):
		form = AddressForm(request.POST)
		if form.is_valid():
			user = User.objects.get(pk=request.user.id)
			user.state = form.cleaned_data.get('state')
			user.address = form.cleaned_data.get('address')
			user.save()
			messages.success(request, 'User address updated')
			return (request, 'core/address.html', {'address_form': form, 'nav_account': 'green'})

		messages.warning(request, 'Fill the user address form appropriately')
		return redirect(reverse('core:address'))


class Settings(LoginRequiredMixin, Base):
	def get_request(self, request):
		user = request.user
		data_form = UserDataForm({'name': user.name, 'whatsapp_number': user.whatsapp_number, 'image': user.image, })
		password_form = UserPasswordForm(user=user)
		return (request, 'core/settings.html', {'data_form': data_form, 'password_form': password_form, 'nav_account': 'green'})


class UserData(LoginRequiredMixin, View):
	def get(self, request):
		return redirect(reverse('core:settings'))

	def post(self, request):
		form = UserDataForm(request.POST, request.FILES)
		if form.is_valid():
			user = User.objects.get(pk=request.user.id)
			user.name = form.cleaned_data.get('name')
			user.whatsapp_number = form.cleaned_data.get('whatsapp_number')
			if form.cleaned_data.get('image'):
				user.image = form.cleaned_data.get('image')
			user.save()
			messages.success(request, 'User data updated')
			return redirect(reverse('core:settings'))

		messages.warning(request, 'Fill the user form appropriately')
		return redirect(reverse('core:settings'))


class UserPassword(LoginRequiredMixin, View):
	def get(self, request):
		return redirect(reverse('core:settings'))

	def post(self, request):
		form = UserPasswordForm(request.POST, user=request.user)
		if form.is_valid():
			user = User.objects.get(pk=request.user.id)
			password = form.cleaned_data.get('password')
			user.password = password
			user.save()
			messages.success(request, 'User password updated')
			return redirect(reverse('core:settings'))

		messages.warning(request, 'Fill the password form appropriately')
		return redirect(reverse('core:settings'))

templates/core/address.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Address{% endblock %}

{% block content %}
  <main>
  <!-- section -->
  <section>
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- col -->
        {% with address='active' %}
          {% include '../include/little_sidebar.html' with address=address %}
        {% endwith %}
        <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Address</h2>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
            </div>
            <div>
              <!-- heading -->
              <h5 class="mb-4">Account details</h5>
              <div class="row">
                <div class="col-lg-5">
                  <!-- form -->
                  <form action="{% url 'core:address' %}" method="post">
                    {% csrf_token %}
                    <!-- input -->
                    <div class="mb-3">
                      <label class="form-label">State</label>
                      {{ address_form.state }}
                      
                    </div>
                    <!-- input -->
                    <div class="mb-5">
                      <label class="form-label">Address</label>
                      {{ address_form.address }}
                      
                    </div>
                    <!-- button -->
                    <div class="mb-3">
                      <button class="btn btn-primary">Save Details</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

{% with address='active' %}
  {% include '../include/little_modelbar.html' with address=address %}
{% endwith %}
{% endblock %}

templates/core/cart.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Cart{% endblock %}

{% block content %}
  <main>
  <!-- section -->
  <section>
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- col -->
        {% with cart='active' %}
          {% include '../include/little_sidebar.html' with cart=cart %}
        {% endwith %}
        <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <!-- heading -->
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Shop Cart</h2>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
            </div>

    <div class="">

      <ul class="list-group list-group-flush">
        <!-- list group -->
        {% for item in cart_items %}
        <li id="product{{ item.product.pk }}" class="list-group-item py-3 ps-0 border-bottom">
          <!-- row -->
          <div class="row align-items-center">
            <div class="col-3 col-md-2">
              <!-- img --> <img src="{{ item.product.image|image_url }}" alt="Ecommerce"
                class="img-fluid"></div>
            <div class="col-3 col-md-4 col-lg-5">
              <!-- title -->
              <a href="{% url 'main:product_detail' pk=item.product.pk %}" class="text-inherit">
                <h6 class="mb-0 ellipsis-oneline">{{ item.product.name }}</h6>
              </a>
              <!-- text -->
              <div class="mt-2 small lh-1"> 
                <a style="cursor: pointer;" onclick="remove_cart('{{ item.product.pk }}')" class="text-decoration-none text-inherit"> 
                <span class="me-md-1 me-0 align-text-bottom d-sm-inline d-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"
                      stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                      class="feather feather-trash-2 text-success">
                      <polyline points="3 6 5 6 21 6"></polyline>
                      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                      </path>
                      <line x1="10" y1="11" x2="10" y2="17"></line>
                      <line x1="14" y1="11" x2="14" y2="17"></line>
                    </svg>
                  </span>
                  <span class="text-muted">Remove</span>
                </a>
                </div>
            </div>
            <!-- input group -->
            <div class="col-3 col-md-4 col-lg-3 p-0">
              <!-- input -->
              <!-- input -->
              <form action="i need to fill this" class="input-group input-spinner  ">
                <input onclick="minus_cart(this, '{{ item.product.pk }}')" type="button" value="-" class="btn btn-sm " data-field="quantity">
                <input type="number" step="1" max="10" value="{{ item.quantity }}" name="quantity"
                  class="quantity-field form-control-sm form-input">
                <input onclick="plus_cart(this, '{{ item.product.pk }}')" type="button" value="+" class="btn btn-sm " data-field="quantity">
              </form>

            </div>
            <!-- price -->
            <div class="col-3 text-lg-end text-start text-md-end col-md-2">
              <span class="fw-bold">₦{{ item.total_price|format_price }}</span>

            </div>
          </div>

        </li>
        {% endfor %}
      </ul>
      <div id="total-price" class="fw-bold mt-3 text-end">
        ₦{{ total }}
      </div>
      <!-- btn -->
      <div class="d-flex justify-content-between mt-4">
        <a href="/products" class="btn btn-primary">Continue Shopping</a>
        <a href="#!" class="btn btn-dark">Checkout</a>
      </div>

    </div>
  </div>
</div>




 
        </div>
      </div>
    </div>
  </section>

</main>

{% with cart='active' %}
  {% include '../include/little_modelbar.html' with cart=cart %}
{% endwith %}

{% endblock %}

templates/core/order_detail.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Your Order{% endblock %}

{% block content %}
 <main class="">
      <div class="container">
        <div class="row mb-8">
        {% with orders='active' %}
          {% include '../include/little_sidebar.html' with orders=orders %}
        {% endwith %}
          <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <!-- page header -->
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Your Order</h2>
              <div>
                <a href="{% url 'core:orders' %}" class="btn btn-light d-md-none d-inline">Orders</a>
                <a href="{% url 'core:orders' %}" class="btn btn-light d-md-inline d-none">Back Order</a>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
          </div>
            </div>

        <!-- row -->
        <div class="row ">
          <div class="col-xl-12 col-12 mb-5">
            <!-- card -->
            <div class="card h-100 card-lg">
              <div class="card-body p-6">
                <div class="d-md-flex justify-content-between">
                  <div class="d-flex align-items-center mb-2 mb-md-0">
                    <h2 class="mb-0">Order ID: {{ order.id }}</h2>
                    <span class="badge bg-secondary ms-2">{{ order.order_status }}</span>
                  </div>
                </div>
                <div class="mt-8">
                  <div class="row">
                    <!-- address -->
                    <div class="col-lg-4 col-md-4 col-12">
                      <div class="mb-6">
                        <h6>Customer Details</h6>
                        <p class="mb-1 lh-lg">{{ order.buyer.name }}<br>
                          {{ order.buyer.email }}<br>
                          {{ order.buyer.whatsapp_number }}</p>
                      </div>
                    </div>
                    <!-- address -->
                    <div class="col-lg-4 col-md-4 col-12">
                      <div class="mb-6">
                        <h6>Shipping Address</h6>
                        <p class="mb-1 lh-lg">{{ order.buyer.address }}<br>
                          {{ order.buyer.state }}<br></p>

                      </div>
                    </div>
                    <!-- address -->
                    <div class="col-lg-4 col-md-4 col-12">
                      <div class="mb-6">
                        <h6>Order Details</h6>
                        <p class="mb-1 lh-lg">Order ID: <span class="text-dark">{{ order.id }}</span><br>
                          Order Date: <span class="text-dark">{{ order.date|date:"F j, Y" }}</span><br>
                          </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

        </div>

      </div>
      </div>
      </div>
    </main>

{% with orders='active' %}
  {% include '../include/little_seller_modelbar.html' with orders=orders %}
{% endwith %}

{% endblock %}

templates/core/orders.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Orders{% endblock %}

{% block content %}
  <main>
  <!-- section -->
  <section>
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- col -->
        {% with orders='active' %}
          {% include '../include/little_sidebar.html' with orders=orders %}
        {% endwith %}
        <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <!-- heading -->
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Your Orders</h2>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
            </div>

            <div class="table-responsive-xxl border-0">
              <!-- Table -->
              <table class="table mb-0 text-nowrap table-centered ">
                <!-- Table Head -->
                <thead class="bg-light">
                  <tr>
                    <th>Order</th>
                    <th>Status</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- Table body -->
                  {% for order in orders %}
                  <tr>
                    <td class="align-middle border-top-0">
                      <a href="{% url 'core:order_detail' pk=order.pk %}" class="text-reset">
                        {{ order.id }}
                      </a>
                    </td>
                     <td class="align-middle border-top-0">
                      <span class="badge bg-secondary">{{ order.order_status }}</span>
                    </td>
                    <td class="align-middle border-top-0">
                      {{ order.date|date:"F j, Y" }}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

</main>

{% with orders='active' %}
  {% include '../include/little_modelbar.html' with orders=orders %}
{% endwith %}

{% endblock %}

templates/core/settings.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Settings{% endblock %}

{% block content %}
  <main>
  <!-- section -->
  <section>
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- col -->
        {% with settings='active' %}
          {% include '../include/little_sidebar.html' with settings=settings %}
        {% endwith %}

        <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Account Setting</h2>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
            </div>
            <div>
              <!-- heading -->
              <h5 class="mb-4">Account details</h5>
              <div class="row">
                <div class="col-lg-5">
                  <!-- form -->
                  <form action="{% url 'core:user_data' %}" method="post" enctype="multipart/form-data">
                  	{% csrf_token %}
                    <!-- input -->
                    <div class="mb-3">
                      <label class="form-label">Name</label>
                      {{ data_form.name }}
                    </div>
                    <!-- input -->
                    <div class="mb-5">
                      <label class="form-label">Whatsapp Number</label>
                      {{ data_form.whatsapp_number }}
                    </div>
                    <div class="mb-5">
                      <label class="form-label">Image</label>
                      {{ data_form.image }}
                    </div>
                    <!-- button -->
                    <div class="mb-3">
                      <button class="btn btn-primary">Save Details</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <hr class="my-10">
            <div class="pe-lg-14">
              <!-- heading -->
              <h5 class="mb-4">Password</h5>
              <form action="{% url 'core:user_password' %}" method="post" class=" row row-cols-1 row-cols-lg-2">
              	{% csrf_token %}
                <!-- input -->
                <div class="mb-3 col">
                  <label class="form-label">New Password</label>
                  {{ password_form.password }}
                  {% if password_form.password.errors %}
                  {% for error in password_form.password.errors %}
                    <span class="text-danger small">{{ error }}</span>
                  {% endfor %}
                  {% endif %}
                </div>
                <!-- input -->
                <div class="mb-3 col">
                  <label class="form-label">Current Password</label>
                  {{ password_form.current_password }}
                  {% if password_form.current_password.errors %}
                  {% for error in password_form.current_password.errors %}
                    <span class="text-danger small">{{ error }}</span>
                  {% endfor %}
                  {% endif %}
                </div>
                <!-- input -->
                <div class="col-12">
                  <p class="mb-4">Can’t remember your current password?<a href="{% url 'login:forgot-password' %}"> Reset your password.</a></p>
                  <button class="btn btn-primary">Save Password</button>
                </div>
              </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
</main>

{% with settings='active' %}
  {% include '../include/little_modelbar.html' with settings=settings %}
{% endwith %}

{% endblock %}