core/urls.py
from django.urls import path
from .views import (Settings, UserData, UserPassword, Address, Orders, OrderDetail, OrderCreate,
		Cart, CartPlus, CartMinus, CartRemove)

app_name = 'core'

urlpatterns = [
    path('cart', Cart.as_view(), name='cart'),
    path('cart-plus/<str:pk>', CartPlus.as_view(), name='cart_plus'),
    path('cart-minus/<str:pk>', CartMinus.as_view(), name='cart_minus'),
    path('cart-remove/<str:pk>', CartRemove.as_view(), name='cart_remove'),
    path('orders', Orders.as_view(), name='orders'),
    path('order-detail/<str:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order-create/<str:pk>', OrderCreate.as_view(), name='order_create'),
    path('address', Address.as_view(), name='address'),
    path('settings', Settings.as_view(), name='settings'),
    path('settings/data', UserData.as_view(), name='user_data'),
    path('settings/password', UserPassword.as_view(), name='user_password'),
]
 

main/urls.py
from django.urls import path
from .views import Index, Products, ProductDetail, EmailSubscribe, ContactUs, BecomeSeller

app_name = 'main'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('become-seller', BecomeSeller.as_view(), name='become_seller'),
    path('email-subscribe', EmailSubscribe.as_view(), name='email_subscribe'),
    path('contact-us', ContactUs.as_view(), name='contact_us'),
    path('products', Products.as_view(), name='products'),
    path('products/<str:pk>', ProductDetail.as_view(), name='product_detail'),
]

mstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('core.urls')),
    path('', include('login.urls')),
    path('seller/', include('seller.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.error_404'
# handler500 = 'main.views.error_500'

seller/urls.py
from django.urls import path
from .views import Dashboard, Products, CreateProduct, UpdateProduct, Orders, OrderDetail, DeleteProduct, Description

app_name = 'seller'

urlpatterns = [
    path('dashboard', Dashboard.as_view(), name='dashboard'),
    path('orders', Orders.as_view(), name='orders'),
    path('orders/<str:pk>', OrderDetail.as_view(), name='order_detail'),
    path('description', Description.as_view(), name='description'),
    path('products', Products.as_view(), name='products'),
    path('products/create', CreateProduct.as_view(), name='create_products'),
    path('products/update/<str:pk>', UpdateProduct.as_view(), name='update_products'),
    path('products/delete/<str:pk>', DeleteProduct.as_view(), name='delete_products'),
]
 

seller/models.py
from django.db import models
from django.http import HttpResponseForbidden

# Create your models here.

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.urls import reverse_lazy


class SellerRequiredMixin(LoginRequiredMixin):
    """
    Custom mixin that requires the user to be logged in, active, and a seller.
    """
    redirect_field_name = 'next'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if not request.user.is_active:
            return redirect_to_login(
                self.request.get_full_path(),
                reverse_lazy('login'),
                self.redirect_field_name
            )
        if not request.user.is_seller: # assuming you have a field called "is_seller" on the User model
            return HttpResponseForbidden() # or any other response you want to return for non-sellers
        return super().dispatch(request, *args, **kwargs)

seller/forms.py
from django import forms
from django import db
from django.contrib import messages
from ckeditor.widgets import CKEditorWidget
from core.models import SubCategory


class DescriptionForm(forms.Form):
	description = forms.CharField(required=False, label='', widget=forms.Textarea(attrs={
		'placeholder':'Description', 'class': 'form-control'
	}))

	def clean_description(self):
		description = self.cleaned_data.get('description')
		if not description:
			raise forms.ValidationError('Provide seller description')
		return description


class ProductForm(forms.Form):
	name = forms.CharField(required=True, label='', max_length=100,  widget=forms.TextInput(attrs={
		'placeholder':'Name', 'class': 'form-control'
	}))

	state = forms.CharField(required=False, label='', max_length=100,  widget=forms.TextInput(attrs={
		'placeholder':'State', 'class': 'form-control'
	}))

	price = forms.CharField(required=True, label='', max_length=100,  widget=forms.NumberInput(attrs={
		'placeholder':'Price', 'class': 'form-control'
	}))
	try:
		MY_CHOICES = [ [i.id, i.name] for i in SubCategory.objects.all() ]
	except (db.utils.ProgrammingError, db.utils.OperationalError):
		MY_CHOICES = [[]]

	sub_category = forms.ChoiceField(required=True, choices=[['', 'Select an option']]+MY_CHOICES, initial='', widget=forms.Select(attrs={
		'placeholder':'Price', 'class': 'form-select'
	}))

	image = forms.ImageField(required=False, label='', widget=forms.FileInput(attrs={
	'class': 'form-control'
	}))

	description = forms.CharField(required=False, label='', widget=CKEditorWidget(attrs={
		'placeholder':'Description', 'class': 'form-control'
	}))

	def clean_price(self):
		price = self.cleaned_data.get('price')
		if not price:
			raise forms.ValidationError('Provide price')
		elif float(price) <= 0:
			raise forms.ValidationError('Price should be above zero')
		return price

	def clean_sub_category(self):
		sub_category = self.cleaned_data.get('sub_category')
		if not sub_category:
			raise forms.ValidationError('Select sub category')
		return sub_category

	def clean_name(self):
		name = self.cleaned_data.get('name')
		if not name:
			raise forms.ValidationError('Name is required')
		return name

seller/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import Http404
from core.models import User, Order, Product, SubCategory, Cart
from .models import SellerRequiredMixin
from main.views import Base
from .forms import ProductForm, DescriptionForm
from utils import paginate_page

# Create your views here.


class Dashboard(SellerRequiredMixin, Base):
	def get_request(self, request):
		num_products = Product.objects.filter(seller=request.user).count()

		# seller_cart_items = Cart.objects.filter(product__seller=request.user) # get cart items (for product of a seller)
		# seller_orders = Order.objects.filter(items__in=seller_cart_items).distinct() # get Orders that have any of the cart products
		# all_seller_cart_items = Cart.objects.filter(product__seller=request.user, order__in=seller_orders)
		# num_buyers = all_seller_cart_items.values('buyer').distinct().count()

		orders = Cart.objects.filter(product__seller=request.user, checked_out=True).order_by('product__ordered')
		num_buyers = orders.values('buyer').distinct().count()
		return (request, 'seller/dashboard.html', {
			'num_products': num_products,
			'num_buyers': num_buyers,
			'order_product': orders,
			'nav_seller': 'green',
		})


class OrderDetail(SellerRequiredMixin, Base):
	def get_request(self, request, pk):
		order = get_object_or_404(Order, pk=pk, items__product__seller=request.user.id)
		return (request, 'seller/order_detail.html', {
			'order': order,
			'nav_seller': 'green',
		})


class Orders(SellerRequiredMixin, Base):
	def get_request(self, request):
		# seller_cart_items = Cart.objects.filter(product__seller=request.user) # get cart items (for product of a seller)
		# seller_orders = Order.objects.filter(items__in=seller_cart_items).distinct() # get Orders that have any of the cart products
		# all_seller_cart_items = Cart.objects.filter(product__seller=request.user, order__in=seller_orders)
		
		orders = Cart.objects.filter(product__seller=request.user, checked_out=True).order_by('product__ordered')
		
		return (request, 'seller/orders.html', {
			**paginate_page(orders, request, Http404, obj='order_product'),
			'nav_seller': 'green',
		})


class Description(SellerRequiredMixin, Base):
	def get_request(self, request):
		user = request.user
		description_form = DescriptionForm({'description': user.description})
		return (request, 'seller/description.html', {'description_form': description_form, 'nav_seller': 'green'})

	def post_request(self, request):
		form = DescriptionForm(request.POST)
		print('not in')
		if form.is_valid():
			print('in in', form.cleaned_data.get('description'))
			user = User.objects.get(pk=request.user.id)
			user.description = form.cleaned_data.get('description')
			user.save()
			messages.success(request, 'User description updated')
			return (request, 'seller/description.html', {'description_form': form, 'nav_seller': 'green'})

		messages.warning(request, 'Fill the user description form appropriately')
		return redirect(reverse('seller:description'))


class DeleteProduct(SellerRequiredMixin, Base):
	def get_request(self, request, pk):
		return redirect(reverse('seller:products'))

	def post_request(self, request, pk):
		try:
			Product.objects.get(pk=pk).delete()
			messages.success(request, 'Product deleted successfully')
			return redirect(reverse('seller:products'))
		except Product.DoesNotExist:
			messages.warning(request, 'Product not deleted')
			return redirect(reverse('seller:products'))


class Products(SellerRequiredMixin, Base):
	def get_request(self, request):
		products = Product.objects.filter(seller=request.user.id).order_by('ordered')
		return (request, 'seller/products.html', {
			**paginate_page(products, request, Http404, obj='products'),
			'nav_seller': 'green',
		})


class CreateProduct(SellerRequiredMixin, Base):
	def get_request(self, request):
		form = ProductForm()
		return (request, 'seller/create_product.html', {'form': form, 'nav_seller': 'green',})

	def post_request(self, request):
		form = ProductForm(request.POST, request.FILES)
		if form.is_valid() and form.cleaned_data.get('sub_category'):
			product = Product()
			product.name = form.cleaned_data.get('name')
			product.state = form.cleaned_data.get('state')
			product.price = form.cleaned_data.get('price')
			product.sub_category = SubCategory.objects.get(pk=form.cleaned_data.get('sub_category'))
			product.description = form.cleaned_data.get('description')
			if form.cleaned_data.get('image'):
				product.image = form.cleaned_data.get('image')
			product.seller = request.user
			product.save()
			messages.success(request, 'Product created successfully')
			return redirect(reverse('seller:products'))

		messages.warning(request, 'Fill the product form appropriately')
		return (request, 'seller/create_product.html', {'form': form})


class UpdateProduct(SellerRequiredMixin, Base):
	def get_request(self, request, pk):
		product = get_object_or_404(Product, pk=pk, seller=request.user.id)
		product_dict = model_to_dict(product)
		del product_dict['ordered']
		del product_dict['is_approved']
		del product_dict['date']
		del product_dict['id']
		form = ProductForm(product_dict)
		return (request, 'seller/update_product.html', {
			'form': form,
			'nav_seller': 'green',
		})

	def post_request(self, request, pk):
		product = get_object_or_404(Product, pk=pk, seller=request.user.id)
		form = ProductForm(request.POST, request.FILES)
		if form.is_valid():
			product.name = form.cleaned_data.get('name')
			product.state = form.cleaned_data.get('state')
			product.price = form.cleaned_data.get('price')
			product.sub_category = SubCategory.objects.get(pk=form.cleaned_data.get('sub_category'))
			product.description = form.cleaned_data.get('description')
			if form.cleaned_data.get('image'):
				product.image = form.cleaned_data.get('image')
			product.save()
			messages.success(request, 'Product updated successfully')
			return redirect(reverse('seller:products'))
		form = ProductForm(instance=product)
		messages.warning(request, 'Fill the product form appropriately')
		return (request, 'seller/update_product.html', {'form': form})

templates/seller/create_product.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Create Product{% endblock %}

{% block style %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

{% block content %}

<main class="">
      <!-- container -->
      <div class="container">
        <!-- row -->
        <div class="row mb-8">
                  {% with products='active' %}
          {% include '../include/little_seller_sidebar.html' with products=products %}
        {% endwith %}
          <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Add <span class="d-md-inline d-none">New</span> Product</h2>
              <div>
                <a href="{% url 'seller:products' %}" class="btn btn-light d-md-none d-inline">Products</a>
                <a href="{% url 'seller:products' %}" class="btn btn-light d-md-inline d-none">Back Product</a>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
          </div>

            </div>


        <!-- row -->
        <div class="row">

          <div class="col-12">
            <!-- card -->
            <div class="card mb-6 card-lg">
              <!-- card body -->
              <div class="card-body p-6 ">
                <h4 class="mb-4 h5">Product Information</h4>
                <form action="{% url 'seller:create_products' %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="row">
                  <!-- input -->
                  <div class="mb-3 col-lg-6">
                    <label class="form-label">Name</label>
                    {{ form.name }}
                  </div>
                  <!-- input -->
                  <div class="mb-3 col-lg-6">
                    <label class="form-label">Sub Category</label>
                    {{ form.sub_category }}
                  </div>
                  <!-- input -->
                  <div class="mb-3 col-lg-6">
                    <label class="form-label">State</label>
                    {{ form.state }}
                  </div>
                  <!-- input -->
                  <div class="mb-3 col-lg-6">
                    <label class="form-label">Price</label>
                    {{ form.price }}
                  </div>
                  <div>
                    <div class="mb-3 col-lg-12 mt-5">
                      <!-- heading -->
                      <h4 class="mb-3 h5">Product Images</h4>

                      {{ form.image }}
                    </div>
                  </div>
                  <!-- input -->
                  <div class="mb-3 col-lg-12 mt-5">
                    <h4 class="mb-3 h5">Product Descriptions</h4>
                    {{ form.description }}
                  </div>
                  <div class="">
                    <button type="submit" class="btn btn-primary">
                      Create Product
                    </button>
                  </div>
                </div>
              </form>
              </div>
            </div>

          </div>


        </div>
      </div>
    </div>
  </div>
    </main>


{% with products='active' %}
  {% include '../include/little_seller_modelbar.html' with products=products %}
{% endwith %}

{% endblock %}

{% block scripts %}
  <script>
    // Initialize CKEditor on the content field
    CKEDITOR.replace('id_description');
  </script>
{% endblock %}

templates/seller/dashboard.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Seller Dashboard{% endblock %}

{% block content %}
<main>
    <section>
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- col -->
        {% with dashboard='active' %}
          {% include '../include/little_seller_sidebar.html' with dashboard=dashboard %}
        {% endwith %}

              <!-- row -->
              <div class="col-lg-9 col-md-8 col-12">
                  <div class="py-6 p-md-6 p-lg-10">
                    <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Dashboard</h2>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
            </div>
                      <!-- card -->
                      <div class="card bg-light border-0 rounded-4">
                          <div class="card-body p-lg-12">
                              <h1>Welcome back! Nime enterprise
                              </h1>
                              <p>Nime enterprise shows your products to the world.</p>
                              <a href="{% url 'seller:create_products' %}" class="btn btn-primary">
                                  Create Product
                              </a>
                          </div>
                      </div>
                  </div>

           
                  <div class="row mt-6">
                      <div class="col-lg-4 col-12 mb-6">
                          <!-- card -->
                          <div class="card h-100 card-lg">
                              <!-- card body -->
                              <div class="card-body p-6">
                                  <!-- heading -->
                                  <div class="d-flex justify-content-between align-items-center mb-6">
                                      <div>
                                          <h4 class="mb-0 fs-5">Products</h4>
                                      </div>
                                      <div
                                          class="icon-shape icon-md bg-light-danger text-dark-danger rounded-circle">
                                          <i class="bi bi-bag fs-5"></i>
                                      </div>
                                  </div>
                                  <!-- project number -->
                                  <div class="lh-1">
                                      <h1 class=" mb-2 fw-bold fs-2">{{ num_products }}</h1>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-12 mb-6">
                          <!-- card -->
                          <div class="card h-100 card-lg">
                              <!-- card body -->
                              <div class="card-body p-6">
                                  <!-- heading -->
                                  <div class="d-flex justify-content-between align-items-center mb-6">
                                      <div>
                                          <h4 class="mb-0 fs-5">Orders</h4>
                                      </div>
                                      <div
                                          class="icon-shape icon-md bg-light-warning text-dark-warning rounded-circle">
                                          <i class="bi bi-cart fs-5"></i>
                                      </div>
                                  </div>
                                  <!-- project number -->
                                  <div class="lh-1">
                                      <h1 class=" mb-2 fw-bold fs-2">{{ order_product|length }}</h1>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-12 mb-6">
                          <!-- card -->
                          <div class="card h-100 card-lg">
                              <!-- card body -->
                              <div class="card-body p-6">
                                  <!-- heading -->
                                  <div class="d-flex justify-content-between align-items-center mb-6">
                                      <div>
                                          <h4 class="mb-0 fs-5">Customer</h4>
                                      </div>
                                      <div class="icon-shape icon-md bg-light-info text-dark-info rounded-circle">
                                          <i class="bi bi-people fs-5"></i>
                                      </div>
                                  </div>
                                  <!-- project number -->
                                  <div class="lh-1">
                                      <h1 class=" mb-2 fw-bold fs-2">{{ num_buyers }}</h1>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
             
              
             
              <!-- row -->
              <div class="row ">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-12 mb-6">
                      <div class="card h-100 card-lg">
                          <!-- heading -->
                          <div class="p-6">
                              <h3 class="mb-0 fs-5">Recent Orders</h3>
                          </div>
                          <div class="card-body p-0">
                              <!-- table -->
                            {% include '../include/orders_list.html' %}
                              
                          </div>
                      </div>
                  </div>
              </div>
              </div>
          </section>
</main>

{% with dashboard='active' %}
  {% include '../include/little_seller_modelbar.html' with dashboard=dashboard %}
{% endwith %}

{% endblock %}

templates/seller/products.html
{% extends '../base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}Seller Products{% endblock %}

{% block content %}
 <main class="">
      <div class="container">
        <div class="row mb-8">
        {% with products='active' %}
          {% include '../include/little_seller_sidebar.html' with products=products %}
        {% endwith %}
          <div class="col-lg-9 col-md-8 col-12">
          <div class="py-6 p-md-6 p-lg-10">
            <!-- page header -->
            <div class="d-flex justify-content-between align-items-center pb-4 pt-md-1 pt-1">
              <!-- heading -->
              <h2 class="mb-0">Products</h2>
              <div>
                <a href="{% url 'seller:create_products' %}" class="btn btn-primary d-md-none d-inline">Add Product</a>
                <a href="{% url 'seller:create_products' %}" class="btn btn-primary d-md-inline d-none">Add Product</a>
              <button class="btn btn-outline-gray-400 text-muted d-md-none btn-icon btn-sm ms-3 " type="button"
              data-bs-toggle="offcanvas" data-bs-target="#offcanvasAccount" aria-controls="offcanvasAccount">
              <i class="bi bi-text-indent-left fs-3"></i>
            </button>
          </div>
            </div>

        <!-- row -->
        <div class="row ">
          <div class="col-xl-12 col-12 mb-5">
            <!-- card -->
            <div class="card h-100 card-lg">
              <!-- card body -->
              <div class="card-body p-0">
                <!-- table -->
                <div class="table-responsive">
                  <table class="table table-centered table-hover text-nowrap table-borderless mb-0 table-with-checkbox">
                    <thead class="bg-light">
                      <tr>
                        <th>Image</th>
                        <th>Product Name</th>
                        <th>Category</th>
                        <th>Sub Category</th>
                        <th>Price</th>
                        <th>Status</th>
                        <th>Create at</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for product in products %}
                      <tr>
                        <td>
                          <a href="{% url 'main:product_detail' pk=product.pk %}"> <img src="{{ product.image|image_url }}" alt=""
                              class="icon-shape icon-md"></a>
                        </td>
                        <td><a href="{% url 'main:product_detail' pk=product.pk %}" class="text-reset">{{ product.name }}</a></td>
                        <td>{{ product.sub_category.name }}</td>
                        <td>{{ product.sub_category.category.name }}</td>
                        <td>₦{{ product.price|format_price }}</td>
                        <td>
                          <span class="badge bg-secondary">{{ product.is_approved_status }}</span>
                        </td>
                        <td>{{ product.date|date:"F j, Y" }}</td>
                        <td>
                          <div class="dropdown">
                            <a href="#" class="text-reset" data-bs-toggle="dropdown" aria-expanded="false">
                              <i class="feather-icon icon-more-vertical fs-5"></i>
                            </a>
                            <ul class="dropdown-menu">
                              <li><a href="#!" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#{{ product.pk }}"><i class="bi bi-trash me-3"></i>Delete</a></li>
                              <li><a class="dropdown-item" href="{% url 'seller:update_products' pk=product.pk %}"><i class="bi bi-pencil-square me-3 "></i>Edit</a>
                              </li>
                            </ul>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>

                </div>
              </div>
              <div class=" border-top d-md-flex justify-content-between align-items-center px-6 py-6">
                <span></span>
                <nav class="mt-2 mt-md-0">
                <ul class="pagination">
                  <li class="page-item {% if not products.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="?page={% if products.has_previous %}{{ products.previous_page_number }}{% else %}1{% endif %}{{ url_args }}" aria-label="Previous">
                      <!-- <i class="feather-icon icon-chevron-left"></i> -->
                      Previous
                    </a>
                  </li>
                  {% for page in page_list %}
                  <li class="page-item "><a class="page-link  {% if page == products.number %}active{% endif %}" href="?page={{ page }}{{ url_args }}">{{ page }}</a></li>
                  {% endfor %}
                  <li class="page-item {% if not products.has_next %}disabled{% endif %}">
                    <a class="page-link" href="?page={% if products.has_next %}{{ products.next_page_number }}{% else %}{{ products.number }}{% endif %}{{ url_args }}" aria-label="Next">
                      <!-- <i class="feather-icon icon-chevron-right"></i> -->
                      Next
                    </a>
                  </li>
                </ul>
              </nav>
              </div>
            </div>

          </div>

        </div>
      </div>
      </div>
      </div>
    </main>

{% for product in products %}
<div class="modal fade" id="{{ product.pk }}" tabindex="-1" aria-labelledby="{{ product.pk }}Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content p-4">
      <div class="modal-header border-0">
        <h5 class="modal-title fs-3 fw-bold" id="{{ product.pk }}Label">Delete Product</h5>

        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="text-center position-relative">
            <img src="{{ product.image|image_url }}" alt="{{ product.name }}" class="mb-3 img-fluid"
                    style="height: 200px">
        </div>
        <div class="mb-5">
            You are about to delete <span class="text-danger">{{ product.name }}</span>
          </div>
        <button class="btn btn-danger" onclick="event.preventDefault(); this.nextElementSibling.submit();">Continue</button>
        <form action="{% url 'seller:delete_products' pk=product.pk %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="_method" value="DELETE">
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% with products='active' %}
  {% include '../include/little_seller_modelbar.html' with products=products %}
{% endwith %}

{% endblock %}